SmartParking.WebClient/SmartParking.WebClient/Controllers/HomeWebClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartParking.WebClient.Controllers
{
    public class HomeWebClientController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SmartParking.WebClient/SmartParking.WebClient/Controllers/ParkingSlotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartParkingSystemAPI.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Threading.Tasks;

namespace SmartParking.WebClient.Controllers
{
    public class ParkingSlotController : Controller
    {
        bool result = false;
        public async Task<ActionResult> Slot_Read([DataSourceRequest]DataSourceRequest request, string parkingID = "")
        {
            if (string.IsNullOrWhiteSpace(parkingID))
            {
                List<SlotModel> slots = new List<SlotModel>();
                using (var client = new HttpClient())
                {
                    string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                    client.BaseAddress = new Uri(url);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage response = await client.GetAsync("api/SlotMaster/GetSlots");
                    if (response.IsSuccessStatusCode)
                    {
                        slots = await response.Content.ReadAsAsync<List<SlotModel>>();
                    }
                }
                DataSourceResult result = slots.ToDataSourceResult(request);
                return Json(result);
            }
            else
            {
                int parkID = int.Parse(parkingID);
                List<SlotModel> slots = new List<SlotModel>();
                using (var client = new HttpClient())
                {
                    string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                    client.BaseAddress = new Uri(url);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage response = await client.GetAsync("api/SlotMaster/GetSlots?id=" + parkID);
                    if (response.IsSuccessStatusCode)
                    {
                        slots = await response.Content.ReadAsAsync<List<SlotModel>>();
                    }
                }
                DataSourceResult result = slots.ToDataSourceResult(request);
                return Json(result);            
            }            
        }

        public async Task<ActionResult> Slot_Destroy([DataSourceRequest]DataSourceRequest request, UserProfileModel user)
        {
            List<UserProfileModel> users = new List<UserProfileModel>();
            using (var client = new HttpClient())
            {
                string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                user.IsActive = false;
                HttpResponseMessage response = await client.PostAsJsonAsync("api/SlotMaster/PostUpdateUserProfile", user);
                if (response.IsSuccessStatusCode)
                {
                    users = await response.Content.ReadAsAsync<List<UserProfileModel>>();
                }
            } 
            DataSourceResult result = users.ToDataSourceResult(request);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public PartialViewResult GetSlotAddForm()
        {
            return PartialView("_AddSlot");
        }
        
        [HttpGet]
        public async Task<PartialViewResult> GetSlotEditForm(int slotID)
        {
            SlotModel slot = new SlotModel();
            using (var client = new HttpClient())
            {   
                string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.GetAsync("api/Slotmaster/GetSlotByID/" + slotID);
                if (response.IsSuccessStatusCode)
                {
                    slot = await response.Content.ReadAsAsync<SlotModel>();
                }
            }
            ViewBag.Mode = "Edit";
            return PartialView("_AddSlot", slot);
        }
        public async Task<JsonResult> GetParkings()
        {
            List<ParkingModel> listParkingModel = new List<ParkingModel>();

            using (var client = new HttpClient())
            {
                string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.GetAsync("api/ParkingMaster/GetParkingMasterList");
                if (response.IsSuccessStatusCode)
                {
                    listParkingModel = await response.Content.ReadAsAsync<List<ParkingModel>>();
                }
            }            
            return Json(listParkingModel, JsonRequestBehavior.AllowGet);
        }
        public PartialViewResult LoadIndex()
        {            
            return PartialView("_ParkingSlotList");
        }

        public async Task<ActionResult> AddSlot(SlotModel slotModel)
        {
           // bool result=false;
            using (var client = new HttpClient())
            {
                string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.PostAsJsonAsync("api/SlotMaster/PostSlotMaster",slotModel);
                if (response.IsSuccessStatusCode)
                {
                    result = await response.Content.ReadAsAsync<bool>();
                }
            }            
            return Json(result);
        }

        public async Task<ActionResult> UpdateSlot(SlotModel slotModel)
        {
            //bool result=false;            
            using (var client = new HttpClient())
            {
                string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.PostAsJsonAsync("api/SlotMaster/PostUpdateSlotMaster", slotModel);
                if (response.IsSuccessStatusCode)
                {
                    result = await response.Content.ReadAsAsync<bool>();
                }
            }
            return Json(result);
        }
    }
}

SmartParking.WebClient/SmartParking.WebClient/Controllers/ParkingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartParkingSystemAPI.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Threading.Tasks;

namespace SmartParking.WebClient.Controllers
{
    public class ParkingsController : Controller
    {
        //
        // GET: /Parkings/

        public async Task<ActionResult> Parkings_Read([DataSourceRequest]DataSourceRequest request)
        {
            List<ParkingModel> parkings = new List<ParkingModel>();
            using (var client = new HttpClient())
            {
                string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.GetAsync("api/ParkingMaster/GetParkingMasterList");
                if (response.IsSuccessStatusCode)
                {
                    parkings = await response.Content.ReadAsAsync<List<ParkingModel>>();
                }
            }

            DataSourceResult result = parkings.ToDataSourceResult(request);
            return Json(result);
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult LoadIndex()
        {
            return PartialView("_ParkingsGrid");
        }
        [HttpGet]
        public PartialViewResult GetParkingAddForm()
        {
            return PartialView("_AddParking");
        }

        [HttpGet]
        public async Task<PartialViewResult> GetParkingEditForm(int parkId)
        {
            ParkingModel parkingToEdit = new ParkingModel();
            using (var client = new HttpClient())
            {
                string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.GetAsync("api/ParkingMaster/GetParkingMaster/" + parkId);
                if (response.IsSuccessStatusCode)
                {
                    parkingToEdit = await response.Content.ReadAsAsync<ParkingModel>();
                }
            }
            ViewBag.Mode = "Edit";
            return PartialView("_AddParking", parkingToEdit);
        }

        public async Task<ActionResult> AddParking(ParkingModel parkingModel)
        {
            bool result = false;
            using (var client = new HttpClient())
            {
                string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.PostAsJsonAsync("api/ParkingMaster/PostParking", parkingModel);
                if (response.IsSuccessStatusCode)
                {
                    result = await response.Content.ReadAsAsync<bool>();
                }
            }
            return Json(result);
        }
                
        public async Task<ActionResult> UpdateParking(ParkingModel parkingModel)
        {
            bool result = false;
            using (var client = new HttpClient())
            {
                string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.PostAsJsonAsync("api/ParkingMaster/PostUpdateParking", parkingModel);
                if (response.IsSuccessStatusCode)
                {
                    result = await response.Content.ReadAsAsync<bool>();
                }
            }
            return Json(result);
        }

    }
}

SmartParking.WebClient/SmartParking.WebClient/Controllers/UserLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using SmartParkingSystemAPI.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace SmartParking.WebClient.Controllers
{
    public class UserLogController : Controller
    {
        //
        // GET: /UserLog/

        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> GetAllUsers()
        {
            List<UserProfileModel> allUsers = new List<UserProfileModel>();
            List<UserProfileModel> allUsersWhoAreActive = new List<UserProfileModel>();
            using (var client = new HttpClient())
            {
                string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                client.BaseAddress = new Uri(url);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.GetAsync("api/UserProfile/GetUserProfileList");
                if (response.IsSuccessStatusCode)
                {
                    allUsers = await response.Content.ReadAsAsync<List<UserProfileModel>>();
                }
                allUsersWhoAreActive=allUsers.Where(usr => usr.IsActive == true).ToList();
            }
            return Json(allUsersWhoAreActive, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> Log_Read([DataSourceRequest]DataSourceRequest request, string userID = "")
        {
            List<SlotTransactionModel> allSlotTransaction = new List<SlotTransactionModel>();
            if (string.IsNullOrWhiteSpace(userID))
            {
               
                using (var client = new HttpClient())
                {
                    string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                    client.BaseAddress = new Uri(url);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage response = await client.GetAsync("api/SlotTransaction/GetSlotTransaction");
                    if (response.IsSuccessStatusCode)
                    {
                        allSlotTransaction = await response.Content.ReadAsAsync<List<SlotTransactionModel>>();
                    }
                }
                DataSourceResult result = allSlotTransaction.ToDataSourceResult(request);
                return Json(result);
            }
            else
            {
                int UserID = int.Parse(userID);                 
                using (var client = new HttpClient())
                {
                    string url = System.Configuration.ConfigurationManager.AppSettings["SmartParkingAPI"];
                    client.BaseAddress = new Uri(url);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage response = await client.GetAsync("api/SlotTransaction/GetSlotTransactionAsUser?userId=" + UserID);
                    if (response.IsSuccessStatusCode)
                    {
                        allSlotTransaction = await response.Content.ReadAsAsync<List<SlotTransactionModel>>();
                    }
                }
                DataSourceResult result = allSlotTransaction.ToDataSourceResult(request);
                return Json(result);
            }
            
        }
    }
}

SmartParking.WebClient/SmartParking.WebClient/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    @Styles.Render("~/Content/kendo/css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    <script src="/Scripts/jquery.validate.js"></script>
    <script src="/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="/Scripts/jquery.unobtrusive-ajax.js"></script>
    @Scripts.Render("~/bundles/kendo")
    <script src="~/Scripts/common.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("User Log", "Index", "UserLog")</li>
                        <li>@Html.ActionLink("User Log By Parking", "Index", "UserLogByParking")</li>
                        <li>@Html.ActionLink("User Management", "Index", "UserManagement")</li>
                        <li>@Html.ActionLink("Parking Management", "Index", "Parkings")</li>
                        <li>@Html.ActionLink("Slot Management", "Index", "ParkingSlot")</li>
                        <li>@Html.ActionLink("About", "About", "HomeWebClient")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "HomeWebClient")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>


    @RenderSection("scripts", required: false)
</body>
</html>*@






<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title - Smart Parking </title>
    @Styles.Render("~/Content/kendo/css")
    @*@Styles.Render("~/Content/css") *@
    @Scripts.Render("~/bundles/jquery")


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/NewCss/ddmenu.css" rel="stylesheet" />
    <script src="~/NewCss/ddmenu.js"></script>
    <style>
        body {
            background: #eee url(NewCss/ddmenu-bg.jpg) no-repeat center 0px;
            padding-top: 90px;
        }
    </style>
    <script src="/Scripts/jquery.validate.js"></script>
    <script src="/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="/Scripts/jquery.unobtrusive-ajax.js"></script>
    @Scripts.Render("~/bundles/kendo")
    <script src="~/Scripts/common.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav id="ddmenu">
        <div class="menu-icon"></div>
        <ul>
            <li class="full-width">
                <span class="top-heading">Parking Management</span>
                <i class="caret"></i>
                <div class="dropdown">
                    <div class="dd-inner">
                        <div class="column">
                            <h3>Parking</h3>
                            @Html.ActionLink("Parking Management", "Index", "Parkings")
                            @Html.ActionLink("Slot Management", "Index", "ParkingSlot")

                        </div>
                       @* <div class="column">
                            <h3>Etiam Massa</h3>
                            <a href="#">Sed interdum</a>
                            <a href="#">Fringilla congue</a>

                        </div>*@
                        <div class="column column260 mayHide">
                            <br />
                            <img src="NewCss/img2.jpg" style="height:150px; width:200px"/>
                        </div>
                    </div>
                </div>
            </li>
            <li class="full-width">
                <span class="top-heading">User Management</span>
                <i class="caret"></i>
                <div class="dropdown">
                    <div class="dd-inner">
                        <div class="column">
                            <h3>User</h3>
                            @Html.ActionLink("User Management", "Index", "UserManagement")
                            @Html.ActionLink("User Log By Parking", "Index", "UserLogByParking")
                        </div>
                        
                        <div class="column column260 mayHide">
                            <br />
                            <img src="NewCss/img1.jpg" style="height:150px; width:200px" />
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </nav>
    <div id="body" style="margin-top:100px; margin-left:150px; margin-right:150px;">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
    </div>
</body> 
</html>